extends:
  - gplane
  - gplane/vue

root: true

parser: vue-eslint-parser
parserOptions:
  parser: babel-eslint

env:
  browser: true

plugins:
  - vue

overrides:
  - files: '*.config.js'
    env:
      node: true
