language: node_js
node_js: stable

cache:
  yarn: true
  directories: node_modules

after_success: yarn build

deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
